### ISSUE TITLE
NavDrawer and Tablayout!!

### ISSUE THREAD

**Issue by btn0513** [bulletyn/bulletyn-android#2]
Need to find a correct way two use these two components together:
1. Set a default menuItem for NavDrawer.
2. Set a default tabitem for TabLayout.
3. TabLayout probably doesn't need multiple fragment classes.
4. Researching on using Toolbar, AppBar, Coordination, NavigationView, FrameLayout, NavigationDrawer together (Elevation and displaying are not correct atm).

**Comment by btn0513** [comment]
1 + 2: Putting both in the main layout to firstly display for users.
3: Need to delete FeaturedFragment, PopularFragment, UpcomingFragment, replace PagerAdapter with FragmentPagerStateAdapter. Then we can reuse a fragment (EventListFragment) for all tab fragments.
4. Solve 1+2 will solve 4.

**Comment by btn0513** [comment]
FragmentPagerAdapter vs FragmentPagerStateAdapter:
http://cammykamal.blogspot.com/2015/05/fragmentstatepageradapter-vs.html
http://www.truiton.com/2013/06/android-fragmentpageradapter-vs-fragmentstatepageradapter/

**Comment by btn0513** [comment]
A demo that we can learn from: https://github.com/chrisbanes/cheesesquare

**Comment by btn0513** [comment]
For Hoang to research:
https://www.reddit.com/r/androiddev/comments/3bar9z/cant_get_the_hang_of_this_collapsible_toolbar/
http://www.reddit.com/r/androiddev/comments/3azmin/android_design_support_library_navigation_drawer/
http://stackoverflow.com/questions/31169137/inflating-appbarlayout-with-toolbar-tablayout#

**Comment by btn0513** [comment]
An existing app that may have  solved the problem: https://github.com/alexdao/Lumivote. The guy who made this app is the one who asked the stackoverflow question above.

**Comment by QuestofIranon** [comment]
Have you resolved this issue?

**Comment by btn0513** [comment]
Hey Josh, I have not resolved this issue. Still looking into it actually.

**Comment by QuestofIranon** [comment]
Ah did you solve it? I had an idea for a fix for the tool and tab bar that I was working on but I think it was having issues when changing between fragments using the slide out panel still.
